apiVersion: v1
kind: Pod
metadata:
  labels:
    jmeter-label: jmeter-master
    jenkins-label: jenkins-slave
spec:
  serviceAccountName: jenkins-release
  containers:
    - name: maven
      image: maven:alpine
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "1024Mi"
          cpu: "250m"
        limits:
          memory: "1536Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-volume
    - name: kubehelm
      image: dtzar/helm-kubectl:2.14.3
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      volumeMounts:
        - mountPath: /root/.helm
          name: helm-volume
  volumes:
    - name: m2-volume
      persistentVolumeClaim:
        claimName: maven-efs-pv-claim
    - name: helm-volume
      persistentVolumeClaim:
        claimName: helm-efs-pv-claim