apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  labels:
    jmeter-label: jmeter-master
    jenkins-label: jenkins-slave
spec:
  serviceAccountName: jenkins-release
  containers:
    - name: distributed-jmeter-master
      image: maven:alpine
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: 1536Mi
          cpu: 400m
        limits:
          memory: 1920Mi
          cpu: 500m
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-volume
    - name: kubehelm
      image: dtzar/helm-kubectl:2.14.3
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 160Mi
          cpu: 125m
      volumeMounts:
        - mountPath: /root/.helm
          name: helm-volume
  volumes:
    - name: m2-volume
      persistentVolumeClaim:
        claimName: maven-efs-pv-claim
    - name: helm-volume
      persistentVolumeClaim:
        claimName: helm-efs-pv-claim