# JMete slave pod deployment default values

#JMeter slave node related configurations cpu, memory,..etc can customized from this file

# POD related configuration
pod:
  # The number of JMete slave pods required
  replicaCount: 3

# JMeter Slave POD resource configuration
resources:
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 1000m
    memory: 4096Mi

# POD image configuration
image:
  repository: "sysco/jmeter-plugins-slave"
  tag: 5.4.3-light
  pullPolicy: IfNotPresent


# JMeter JVM memory configuration
jmeter:
  xms:
    #  Xms<size>        set initial Java heap size
    memory: 3072M
  xmx:
    #  Xmx<size>        set maximum Java heap size
    memory: 3584M
